name: Hello World
author: Vitor
description: 'Greet someone and record the time'
inputs:
  who_to_greet:
    description: 'Name of the person to greet'
    required: true
    default: 'World'
outputs:
  time:
    description: 'The time we greeted you'
runs:
  using: 'node20'
  main: dist/index.js
  pre: setup.js
  pre-if: runner.os == 'linux'
  post: teardown.js
  post-if: runner.os == 'linux'
