name: Caching and Artifacts

on:
  workflow_dispatch:

jobs:
  use-axios:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install dependencies
        run: npm install
      - name: Use axios
        uses: actions/github-script@v7
        with:
          script: |
            const axios = require('axios');
            cosnt res = await axios("https://icanhazdadjoke.com/", {
              headers: {
                Accept: 'text/plain'
              }
            });
            console.log(res.data);
