name: Checkout repo
on: [push]

jobs:
  checkout-and-display-files:
    runs-on: ubuntu-latest
    steps:
      - name: Display files before
        run: ls -la
      - name: Checkout repository manually
        run: |
          git init
          git remote add origin "https://$GITHUB_ACTOR:${{ secrets.GITHUB_TOKEN }}@github.com/$GITHUB_REPOSITORY.git"
          git fetch origin
          git checkout $GITHUB_SHA

      # - name: Checkout repository
      #   uses: actions/checkout@v2
      - name: Display files after
        run: ls -la
