name: Concurrency 1
run-name: Concurrency 1 (${{ inputs.environment }})

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment'
        required: true
        type: environment

concurrency:
  group: ${{ github.workflow }}-${{ github.event.inputs.environment }}-concurrency-key
  cancel-in-progress: true
jobs:
  sleep:
    runs-on: ubuntu-latest
    steps:
      - name: Sleep
        run: sleep 10
