name: Dynamic Matrix
on:
  workflow_dispatch:
    inputs:
      os:
        description: 'Operating System'
        required: true
        default: 'ubuntu-latest,windows-latest'

      node-version:
        description: 'Node Version'
        required: true
        type: string
        default: '14,16,18'

jobs:
  prepare-matrix:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.matrix-result.outputs.result }}
    steps:
      - uses: actions/github-script@v7
        id: matrix-result
        with:
          script: |
            const os = '${{ github.event.inputs.os }}'.split(',');
            const nodeVersion = '${{ github.event.inputs.node-version }}'.split(',');

            return { os: os, 'node-version': nodeVersion};
          result-encoding: json
      - run: echo "${{ steps.matrix-result.outputs.result }}"
      - run: echo "step-output=value" >> $GITHUB_OUTPUT
        id: step-1
      - run: echo "step-output=value 2" >> $GITHUB_OUTPUT
        id: step-2
      - run: |
          echo "${{steps.step-1.outputs.step-output}}"
          echo "${{steps.step-2.outputs.step-output}}"
  node-matrix:
    needs: prepare-matrix
    strategy:
      matrix:
        os: ${{ fromJson(needs.prepare-matrix.outputs.matrix).os}}
        node-version: ${{ fromJson(needs.prepare-matrix.outputs.matrix).node-version }}
    runs-on: ${{ matrix.os }}
    steps:
      - run: echo "This is an experimental run"
      - run: node -v
      - uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version}}
      - run: node -v
