name: Repository Events

on:
  push:
  pull_request:
    types:
      - opened
      - synchronize
  issues:
    types:
      - opened

jobs:
  checkout-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: |
          echo $GITHUB_SHA
          echo $GITHUB_REF
