name: Expressions and Context
run-name: 'Expressions and Context by ${{ github.actor }}, event: ${{ github.event_name }}'

on:
  - push
  - pull_request
  - issues
  - workflow_dispatch

jobs:
  expressions-and-context:
    runs-on: ubuntu-latest
    steps:
      - name: Expressions
        id: expressions
        run: |
          echo ${{ 1 }}
          echo ${{ 'This is a string' }}
          echo ${{ null }}
          echo ${{ true }}
          echo ${{ 1 > 0 }}
          echo ${{ true && false }}

      - name: Dump Context
        id: context
        run: |
          echo '${{ toJson(github) }}'
          echo '${{ toJson(job) }}'
          echo '${{ toJson(secrets) }}'
          echo '${{ toJson(steps) }}'
          echo '${{ toJson(runner) }}'
