name: Matrix
on: [push]

jobs:
  node-matrix:
    continue-on-error: false
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
        node-version: [14, 16, 18]
        include:
          - os: ubuntu-latest
            is-ubuntu: true
          - os: macos-latest
            node-version: 18
          - experimental: false
          - os: ubuntu-latest
            node-version: 18
            experimental: true
          - os: ubuntu-latest
            node-version: 20
        exclude:
          - os: ubuntu-latest
            node-version: 14
      fail-fast: true
    #   max-parallel: 3
    runs-on: ${{ matrix.os }}
    steps:
      - if: matrix.experimental == 'true'
        run: exit 1
      - run: echo "This is an experimental run"
      - run: node -v
      - run: echo "${{ toJson(matrix) }}"
      - uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version}}
      - run: node -v
