name: Reusable Workflow

on:
  workflow_call:
    outputs:
      date:
        description: 'Date Output'
        value: ${{ jobs.generate-output.outputs.date }}

jobs:
  nested-workflow-call:
    uses: gh-actions-org/workflows/.github/workflows/reusable-workflow.yaml@main
    with:
      name: 'NestedRun'
    secrets:
      access-token: ${{ secrets.ACCESS_TOKEN }}
  generate-output:
    runs-on: ubuntu-latest
    outputs:
      date: ${{ steps.generate-output.outputs.date }}
    steps:
      - name: Generate Output
        run: echo "date=$(date)" >> $GITHUB_OUTPUT
        id: generate-output
