name: Stale Issues and PRs

on:
  schedule:
    - cron: '0 14 * * *'
    - cron: '0/5 * * * *' # just for testing - minimum interval is every 5 minutes

jobs:
  stale:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/stale@v9
        with:
          stale-issue-message: 'This issue is stale because it has been open for 60 days with no activity.'
          stale-pr-message: 'This PR is stale because it has been open for 60 days with no activity.'
          days-before-stale: 1
          days-before-close: 2
