name: Status Check Functions

on: [push]

jobs:
  job-1:
    runs-on: ubuntu-latest
    steps:
      - name: Step 1
        run: sleep 20

      - name: Fail step
        id: fail-step
        run: exit 1

      - name: Runs on Failure
        if: failure() && steps.fail-step.conclusion == 'failure'
        run: echo "This job runs only when fail step fails"

      - name: Runs on Success
        # This is not necessary, as the job runs only on success by default
        if: success()
        run: echo "This job runs only on success"

      - name: Always Runs
        # This does not run if the job is cancelled
        # if: success() || failure()
        if: always()
        run: echo "This job always runs"

      - name: Runs When cancelled
        if: cancelled()
        run: echo "This job runs only when cancelled"
  job-2:
    runs-on: ubuntu-latest
    needs: job-1
    if: failure()
    steps:
      - run: echo 'Job 2 run'
