name: Using reusable workflows

on:
  workflow_dispatch:
    inputs:
      name:
        description: 'Name'
        required: true
        type: string
        default: 'Mona'

jobs:
  calling-reusable-workflow:
    uses: gh-actions-org/workflows/.github/workflows/reusable-workflow.yaml@main
    with:
      name: ${{ github.event.inputs.name }}
    secrets:
      access-token: ${{ secrets.ACCESS_TOKEN }}
