name: Variables and Secrets
on: [push]

jobs:
  log-variables-and-secrets:
    runs-on: ${{vars.JOBS_RUNNER}}
    environment: 'staging'
    env:
      BOOLEAN_SECRET: ${{ secrets.BOOLEAN_SECRET}}
      ENV_LEVEL_VAR: ${{ vars.ENV_LEVEL_VAR }}
      REPO_LEVEL_VAR: ${{ vars.REPO_LEVEL_VAR}}
      ORG_LEVEL_VAR: ${{ vars.ORG_LEVEL_VAR}}
    steps:
      - name: Run only if BOOLEAN_SECRET is true
        if: env.BOOLEAN_SECRET == 'true'
        run: echo "This step runs only if BOOLEAN_SECRET is true"
      - name: Log Environment Variables
        run: |
          echo "${{ vars.JOBS_RUNNER}}"
          echo "ENV_LEVEL_VAR: $ENV_LEVEL_VAR"
          echo "REPO_LEVEL_VAR: $REPO_LEVEL_VAR"
          echo "ORG_LEVEL_VAR: $ORG_LEVEL_VAR"

  decrypt-file:
    runs-on: ${{vars.JOBS_RUNNER}}
    steps:
      - uses: actions/checkout@v4
      - name: Decrypt file
        env:
          PASSPHRASE: ${{ secrets.PASSPHRASE }}
        run: |
          mkdir $HOME/secrets
          gpg --quiet --batch --yes --decrypt --passphrase="${PASSPHRASE}" --output $HOME/secrets/secrets.json secrets.json.gpg

      - name: Read decrypted file
        run: cat $HOME/secrets/secrets.json
